name: Java CI with Maven

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Install Playwright system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libdbus-1-3 \
          libdrm2 \
          libgbm1 \
          libgtk-3-0 \
          libnspr4 \
          libnss3 \
          libxcomposite1 \
          libxdamage1 \
          libxfixes3 \
          libxkbcommon0 \
          libxrandr2 \
          xvfb \
          fonts-noto-color-emoji \
          libcairo2 \
          libpango-1.0-0 \
          libpangocairo-1.0-0 \
          libgdk-pixbuf2.0-0 \
          libx11-6 \
          libx11-xcb1 \
          libxcb1 \
          libxext6 \
          libxcb-dri3-0 \
          libxcursor1 \
          libxi6 \
          libxtst6 \
          libglib2.0-0 \
          libpulse0 \
          libsoup2.4-1 \
          libopus0 \
          libwebp7 \
          libsecret-1-0 \
          libgles2

    - name: Verify Playwright Dependencies
      run: |
        ldd $(find /usr/lib -name "libgtk-3.so.0") || echo "Dependency check failed"
        playwright --version

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests

    - name: Install Playwright Browsers
      run: |
        rm -rf ~/.cache/playwright
        mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install chromium"

    - name: Run Tests (headless with xvfb)
      run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" mvn test -e -X

    - name: Generate Allure Report
      if: always()
      run: mvn allure:report -e -X

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          target/surefire-reports/
          target/allure-results/
          target/allure-report/
          playwright-report/
          test-results/
        retention-days: 7
