name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Install Playwright system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libdbus-1-3 \
          libdrm2 \
          libgbm1 \
          libgtk-3-0 \
          libnspr4 \
          libnss3 \
          libxcomposite1 \
          libxdamage1 \
          libxfixes3 \
          libxkbcommon0 \
          libxrandr2 \
          xvfb \
          fonts-noto-color-emoji \
          fonts-freefont-ttf \
          libcairo2 \
          libpango-1.0-0 \
          libpangocairo-1.0-0 \
          libgdk-pixbuf2.0-0 \
          libx11-6 \
          libx11-xcb1 \
          libxcb1 \
          libxext6 \
          libxcb-dri3-0 \
          libxcursor1 \
          libxi6 \
          libxtst6 \
          libglib2.0-0 \
          libasound2-dev \
          libpulse0 \
          libsoup2.4-1 \
          libvpx8 \
          libopus0 \
          libwebp7 \
          libenchant-2-2 \
          libsecret-1-0 \
          libhyphen0 \
          libgles2

    - name: Build project with Maven (skip tests)
      run: mvn -B package --file pom.xml -DskipTests

    - name: Install Playwright Browsers
      run: |
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 mvn exec:java -e \
          -Dexec.mainClass=com.microsoft.playwright.CLI \
          -Dexec.args="install --with-deps chromium"

    - name: Run Playwright Tests
      run: mvn test

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: |
          playwright-report/
          test-results/
        retention-days: 30
